### PR TITLE
Make the Keyboard smaller and Setup GitHub workflows with artifact upload

### PR DESCRIPTION
**Pull request by user0-07161**
The Icons are replaced with one Icon, with reduce size from 26kb to 23kb. Also GitHub workflows are settet up to build debug APK for Testing without using an PC.

### CODE REVIEW

**Comment by user0-07161** [comment]
If the Icon quality isn't good enough, ask me, i have the Icon in better qualities.

**Comment by rkkr** [comment]
Due to apk bundles icon count doesn't really matter.

**Comment by user0-07161** [comment]
Yes, but If it isn't an App bundle it's smaller.

**Comment by rkkr** [comment]
Then making a v26 apk would have better results.

**Comment by user0-07161** [comment]
@rkkr Is now v26 apk with 24kb size.

**Comment by user0-07161** [comment]
[Here](https://github.com/user0-tb/tiny-keyboard/suites/17251129477/artifacts/985490659) is an Test apk

**Comment by user0-07161** [comment]
@rkkr You can review the pr now.

**Comment by rkkr** [comment]
This is all a mess. I'm not going to use Github Tasks, you've removed <26 API resources breaking older androids and swapped icons. And all you gained is 2kb.

**Pull request closed without merging**
